# Generated by Django 4.2.7 on 2023-12-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.producto')),
                ('tipo', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=50)),
            ],
            bases=('stock.producto',),
        ),
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.producto')),
                ('tipo', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('origen', models.CharField(max_length=20)),
            ],
            bases=('stock.producto',),
        ),
        migrations.CreateModel(
            name='Sable',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.producto')),
                ('medida', models.CharField(max_length=10)),
                ('color_sable', models.CharField(max_length=50)),
                ('color_luz', models.CharField(max_length=50)),
            ],
            bases=('stock.producto',),
        ),
    ]
